
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('students').del()
    .then(function () {
      // Inserts seed entries
      return knex('students').insert([
        {
          "id": 1,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Wolfgang",
          "lastName": "Stein",
          "totalScore": 33,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 2,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Jack",
          "lastName": "Mudd",
          "totalScore": 36,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 3,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Beastie",
          "lastName": "Boiz",
          "totalScore": 39,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 4,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Bonethugs",
          "lastName": "Nharmony",
          "totalScore": 38,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 5,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Pusha",
          "lastName": "Tee",
          "totalScore": 38,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 6,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Snoop",
          "lastName": "Dawg",
          "totalScore": 35,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 7,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Massimo",
          "lastName": "Maci",
          "totalScore": 37,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 8,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Kermit",
          "lastName": "Thefrog",
          "totalScore": 33,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 9,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Olive",
          "lastName": "Juice",
          "totalScore": 34,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 10,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Robert",
          "lastName": "Russo",
          "totalScore": 33,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 11,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Judy",
          "lastName": "Russo",
          "totalScore": 35,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 12,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Elaine",
          "lastName": "Jones",
          "totalScore": 36,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 13,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Kim",
          "lastName": "Worthington",
          "totalScore": 37,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 14,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Brian",
          "lastName": "Worthington",
          "totalScore": 36,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 15,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Christopher",
          "lastName": "Worthington",
          "totalScore": 35,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 16,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Jessica",
          "lastName": "Jones",
          "totalScore": 39,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 17,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Robert",
          "lastName": "Jones",
          "totalScore": 30,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 18,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Kathy",
          "lastName": "Minassian",
          "totalScore": 37,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 19,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Seta",
          "lastName": "Buchter",
          "totalScore": 31,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 20,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Christina",
          "lastName": "Buchter",
          "totalScore": 34,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 21,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Rodger",
          "lastName": "Rabbit",
          "totalScore": 34,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 22,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Gonzo",
          "lastName": "Newman",
          "totalScore": 39,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 23,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Alex",
          "lastName": "Hough",
          "totalScore": 38,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 24,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Carly",
          "lastName": "Mandell",
          "totalScore": 33,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        },
        {
          "id": 25,
          "test_id": 1,
          "educator_id": 1,
          "firstName": "Prudence",
          "lastName": "Compatriot",
          "totalScore": 31,
          "receptiveScore": null,
          "expressiveScore": null,
          "socialSkillsScore": null,
          "redFlags": null
        }
      ]);
    });
};
